# Generated by Django 4.1.6 on 2024-03-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFacebookModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id user facebook')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Usuario Facebook',
                'verbose_name_plural': 'Usuarios Facebook',
                'db_table': 'user_facebook',
            },
        ),
    ]
