# Generated by Django 4.1.6 on 2024-03-23 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usershopmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFacebookModel',
        ),
    ]
