# Generated by Django 4.1.6 on 2024-03-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_userfacebookmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClientModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id client')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Usuario Cliente',
                'verbose_name_plural': 'Usuarios Cliente',
                'db_table': 'user_client',
            },
        ),
    ]
