# Generated by Django 4.1.6 on 2024-03-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userclientmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclientmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id user client'),
        ),
    ]
