# Generated by Django 4.1.6 on 2024-03-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userclientmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclientmodel',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userclientmodel',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userclientmodel',
            name='marital_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userclientmodel',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userclientmodel',
            name='preferred_payment_method',
            field=models.CharField(default='', max_length=100),
        ),
    ]
