# Generated by Django 4.1.6 on 2024-03-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userclientmodel_age_userclientmodel_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoreModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id user store')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
                'db_table': 'store',
            },
        ),
    ]
