# Generated by Django 4.1.6 on 2024-03-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userproductmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproductmodel',
            name='UserstoreModel',
        ),
    ]
