# Generated by Django 4.1.6 on 2024-03-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_userproductmodel_userstoremodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmployeeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id user employee')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=100)),
                ('identification_number', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employee',
            },
        ),
    ]
