# Generated by Django 4.1.6 on 2024-03-27 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_useremployeemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremployeemodel',
            name='userstoreModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_employee', to='core.userstoremodel'),
        ),
    ]
