# Generated by Django 4.1.6 on 2024-03-28 21:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userproductmodel_userstoremodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransaccionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id transaccion')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('userclientModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_transaccion', to='core.userclientmodel')),
                ('userproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_transaccion', to='core.userproductmodel')),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transaccions',
                'db_table': 'transaccion',
            },
        ),
    ]
